# Generated by Django 3.1 on 2021-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
